name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # fetch the Git tags for sbt-dynver and sbt-version-policy to work correctly
        fetch-depth: 0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: npm install
      run: npm install
    - name: Run JVM tests
      run: sbt tastyQueryJVM/test
    - name: Run JS tests
      run: sbt tastyQueryJS/test
    - name: Run scalafmt check
      run: sbt scalafmtCheck
    - name: Run version policy check
      run: sbt versionPolicyCheck
