name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17' ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: npm install
      run: npm install
    - name: Run JVM tests
      run: sbt tastyQueryJVM/test
    - name: Run JS tests
      run: sbt tastyQueryJS/test
    - name: Run examples
      run: sbt "examples/run simple_trees.TypeMember"
    - name: Run scalafmt check
      run: sbt scalafmtCheck
